apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    appdb: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: mysql
  template:
    metadata:
      labels:
        appdb: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    appdb: mysql